version: "3"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - "frontend"
    
  db:
    image: postgres:9.4
    environment:
        POSTGRES_PASSWORD: mypass
        POSTGRES_HOST_AUTH_METHOD: trust
        PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - "backend"
    
  vote:
    image: bretfisher/examplevotingapp_vote
    ports:
      - "5000:80"
    networks:
      - "frontend"
    depends_on:
      - "redis"
      - "traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vote.rule=Host(`vote.trycloud.co.in`)"
      - "traefik.http.routers.vote.entrypoints=websecure"
      - "traefik.http.routers.vote.tls.certresolver=myresolver"    
    
    
  result:
    image: bretfisher/examplevotingapp_result
    ports:
      - "5001:80"
    networks:
      - "backend"
    depends_on:
      - "db"
      - "traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.result.rule=Host(`result.trycloud.co.in`)"
      - "traefik.http.routers.result.entrypoints=websecure"
      - "traefik.http.routers.result.tls.certresolver=myresolver"  
    
    
  worker:
    image: bretfisher/examplevotingapp_worker
    networks:
      - "frontend"
      - "backend"

  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=info@trycloud.co.in"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
        - "frontend"
        - "backend"  
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.trycloud.co.in`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"      
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=samim:$$apr1$$NU7Jf3H0$$eedQDYYuQTYpuEUwB.zs.0"
  
  
    
networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge
volumes:
    db-data:
        driver: local
